### ISSUE TITLE
Stop Echo in Echo

### ISSUE THREAD

**Issue by nemani** [meetmangukiya/err-you-cobot#6]

**Comment by meetmangukiya** [comment]
We can have an upstream fix as well.

**Comment by nemani** [comment]
or maybe ask the bot to never respond to itself and coala-bot.
What say?

**Comment by meetmangukiya** [comment]
yeah, that is a better thing to do I guess

**Comment by meetmangukiya** [comment]
@nemaniarjun actually the bot doesn't respond to it messages, but it is the backend problem :point_up: [January 6, 2017 9:13 PM](https://gitter.im/errbotio/errbot?at=586fbb1796a565f84407fde6)
